### ISSUE TITLE
Find by ObjectId

### ISSUE THREAD

**Issue by cipriantarta** [qlik-oss/core-grpc-mongodb-connector#129]
Is there any way to pass an ObjectId as a filter.

I have this statement:
...
`SQL { "collection": "events", "find": {"customer_id": ObjectId("5bbf578465cba11410aab79c")}, "options": {"fields":{"customer_id": 1, "title": 1}} };`
...

However, nothing gets loaded in the app.
If I remove the condition, then the data gets loaded, but I do want to filter it tho.

Thanks

**Comment by axelssonHakan** [comment]
The issue is that the "Select" statement is referring the `ObjectId` class (BSON ObjectId type) that isn't "re-mapped" to a object in the connector.

Since this is "only" an example connector I don't think this is anything we will support in the near future.

On possible solution would be to include the ObjectId class and make a new parameter to map against the scenario
```
const { ObjectId } = require('mongodb');
...
            if (parameters.aggregate) {
              console.log(' --- Aggregate');
              cursor = collection.aggregate(parameters.aggregate, parameters.options || {});
            } else if (parameters.objectId) {
              console.log(' --- ObjectId');
              cursor = collection.find({ _id: ObjectId(parameters.objectId) });
            } else {
              console.log(' --- Find');
              cursor = collection.find(parameters.find || {}, parameters.options || {});
            }
```
```
    sql { "collection": "airports", "objectId": "5cd943cbc2df08ef52b71fd0"};`;
```

Another and more generic solution is to use the *POWER* of Qlik Associative Engine either filtering the data on load (all data is filtered on Engine side).
```
    const script = `
    lib connect to "mongodb";
    Airports:
    sql { "collection": "airports", "find": {}};
    
    Filter:
    NoConcatenate
    LOAD *
    resident Airports
    where _id = '5cd943cbc2df08ef52b71fd0';

    drop table Airports;
    `;
```
Or filtering it while you are fetching the data from the Engine using selections

**Comment by axelssonHakan** [comment]
If you have any questions on how to utilize the **Qlik Associative Engine** I would recommend posting your use case/questions at the Qlik Branch Slack channel:
https://qlik-branch.slack.com/messages/CA243EQ92

**Comment by axelssonHakan** [comment]
Please reopen or reach out on the branch slack if you have further questions
